apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    name: busybox
    hello: test
spec:
  containers:
  - image: 192.168.1.130:5000/busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
