apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    name: app1
spec:
  selector:
    name: app1
  type: NodePort
  ports:
  - port: 8181
    name: http
    nodePort: 30001
  - port: 8101
    name: ssh
    nodePort: 30002
