apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    name: app2
spec:
  selector:
    name: app2
  type: NodePort
  ports:
  - port: 8181
    name: http
    nodePort: 30003
  - port: 8101
    name: ssh
    nodePort: 30004
