id: app1
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: app1
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: app1
        containers:
          - name: app1
            image: flaviof/app1
            cpu: 1000
            volumeMounts:
              - name : "maven-repo"
                mountPath: "/root/.m2/repository"
                readOnly: false
            ports:
              - name: hazelcast
                containerPort: 5701
              - name: http
                containerPort: 8181
              - name: jolokia
                containerPort: 8778
        volumes:
          - name: maven-repo
            source:
              hostDir:
                path: /home/core/.m2/repository
    labels:
      name: app1
      cellar: "true"

